apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: kube-system
spec:
  storageClassName: standard
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/pv01